#!/usr/bin/zsh

# ___System info___
alias path='echo -e ${PATH//:/\\n}'

# ___Network info___
alias localip="ipconfig getifaddr en0"

# ___Shell tools___
alias reload="exec ${SHELL} -l"

# ___Applications___
alias safari="open -a Safari"
alias spotify="open -a Spotify"

# ___Listing files___
if ls --color >/dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
else # macOS `ls`
	colorflag="-G"
	export LSCOLORS='BxBxhxDxfxhxhxhxhxcxcx'
fi

alias l="ls -lF ${colorflag}"                             # List all files colorized in long format
alias la="ls -lAF ${colorflag}"                           # List all files colorized in long format, excluding . and ..
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'" # List only directories
alias ls="command ls ${colorflag}"                        # Always use color output for `ls`
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# ___Time tools___
alias now='date -u +"%Y-%m-%dT%H:%M:%SZ"'
alias week='date +%V'

# ___Navigation___
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cdb="cd -"
alias cddf="cd $DOTFILES"

# ___Git___
alias ga="git add"
alias gaa="git add ."
alias gs="git status"
alias gl="git log --pretty=oneline -n 20 --graph --abbrev-commit"
alias gpl="git pull --rebase"
alias gps="git push"
alias gpsf="git push --force-with-lease"
alias gpsb="git push -u origin"
alias gd="git diff"
alias gst="git stash"
alias gsta="git stash apply"
alias gstp="git stash pop"
alias gcm="git commit -m"
alias gcma="git commit --amend"
alias gcmane="git commit --amend --no-edit"
alias gcb="git checkout -b"
alias gc="git checkout"
alias gbl="git branch -l"
alias gbd="git branch -D"
alias gbdp="git branch -D $(git name-rev @{-1} --name-only | sed 's:.*/::')"
alias gbda="git checkout master && git branch | grep -v '^*' | xargs git branch -D"
alias grss="git restore --staged"
alias grbc="git rebase --continue"
alias gb="git checkout -"
alias grh="git reset --soft HEAD^1"

# ___Github___
alias ghprc="gh pr create --assignee drieshooghe --label=\"team red\""
alias ghprcd="gh pr create --draft --assignee drieshooghe --label=\"team red\""
alias ghpra="gh pr list --label dependencies | cut -f 1 | xargs -I{} gh pr review {} --approve"
alias ghbs="open -a safari https://www.github.com/CHEQROOM/services"
alias ghbw="open -a safari https://www.github.com/CHEQROOM/web"

# ___NPM___
alias nr="npm run"
alias nrt="npm run test"
alias ni="npm install"
alias nid="npm install -D"
alias nrm="npm rm"
alias nu="npm update"

# ___Yarn___
alias yr="yarn run"
alias yrs="yarn run start"
alias yrt="yarn run test"
alias yrl="yarn run lint"
alias yrlf="yarn run lint --fix"
alias yi="yarn install"
alias ya="yarn add"
alias yad="yarn add -D"
alias yrm="yarn remove"
alias yu="yarn upgrade"
alias yl="yarn list --depth=0"

alias ygi="yarn global install"
alias yga="yarn global add"
alias ygrm="yarn global remove"
alias ygu="yarn global upgrade"
alias ygl="yarn global list --depth=0"

# ___Docker___
alias dkcu="docker-compose up"
alias dkcud="docker-compose up -d"
alias dkcd="docker-compose down"
alias dkr="docker run"
alias dks="docker stop"
alias dksl="docker stop $(docker ps --latest -q)"
alias dksa="docker kill $(docker ps -q)"
alias dkrm="docker rm"
alias dkl="docker ps"

# ___Dev tools___
alias gms="gitmoji --search"
alias nms="du -sh ./node_modules/* | sort -nr | grep '\dM.*'" # Check size of node_modules
