# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

# ZSH settings
HISTFILE=~/.zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE

# Load the shell dotfiles
for file in ~/.config/shell/{path,exports,functions,aliases}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Load the shell libraries
for file in ~/.config/libs/*; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


# Use partial history search with the arrow keys
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# Enable Z tab completion
autoload -U compinit && compinit
zstyle ':completion:*' menu select

