name: CI dotfiles

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Lint
        uses: azohra/shell-linter@latest

      - name: Test
        run: ./bootstrap.sh
